app:
  jwtSecret: jwtMySecretKey
  jwtExpiration: 86400
spring:
  datasource:
    url: JDBC_DATABASE_URL=jdbc:postgresql://ec2-54-83-17-151.compute-1.amazonaws.com:5432/d4bllnds9gf5ns
    username: aopbvcxkhlxezz
    password: cadd53c52845124a1fa234faeb423af79496c2fc9e0780be55d1f4b067f2a681